stages:
  - build
  - test
  - deploy
  - cleanup

before_script:
  - docker info

build_dev_image:
  stage: build
  script:
    - echo "[build] COMMIT_ID $CI_BUILD_REF"
    - docker build -t cm-dev-04.bwcmtg.com:5000/retail-portal:$CI_BUILD_REF .
  only:
    - master
  tags:
    - development,docker,retail-portal
    
build_prod_image:
  stage: build
  script:
    - echo "[build prod] COMMIT_ID $CI_BUILD_REF"
    - docker build --build-arg RAILSENV="production" --build-arg RACKENV="production" -t cm-dev-04.bwcmtg.com:5000/retail-portal:$CI_BUILD_REF .
  only:
    - production
  tags:
    - production

test_dev_image:
  stage: test
  script:
    - echo "[test] COMMIT_ID $CI_BUILD_REF"
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose.yml up -d
    - docker exec chmretailwebsite_web_1 env
    - docker exec chmretailwebsite_web_1 foreman run -e test.env bundle exec rake db:drop db:create db:schema:load
    - docker exec chmretailwebsite_web_1 foreman run -e test.env bundle exec rspec
    - docker exec chmretailwebsite_web_1 foreman run -e test.env bundle exec cucumber
    - docker-compose -f docker-compose.yml stop
  only:
    - master
  tags:
    - development,docker,retail-portal

test_prod_image:
  stage: test
  script:
    - echo "[test prod] COMMIT_ID $CI_BUILD_REF"
    - echo "Skipping prod rspec tests given issues with testing prod and rpsec presence"
  only:
    - production
  tags:
    - production

deploy_dev_image:
  stage: deploy
  script:
    - echo "[deploy] COMMIT_ID $CI_BUILD_REF"
    - docker tag cm-dev-04.bwcmtg.com:5000/retail-portal:$CI_BUILD_REF cm-dev-04.bwcmtg.com:5000/retail-portal:dev-latest
    - docker push cm-dev-04.bwcmtg.com:5000/retail-portal:$CI_BUILD_REF
    - docker push cm-dev-04.bwcmtg.com:5000/retail-portal:dev-latest
    - scp $CI_PROJECT_DIR/*.yml devops@dev-www.commercehomemortgage.com:~/services/
    - ssh -v devops@dev-www.chmmarketingportal.com "cd /home/devops/services && ./retail-portal-deploy.sh $CI_BUILD_REF"
  only:
    - master
  tags:
    - development,docker,retail-portal
    
deploy_prod_image:
  stage: deploy
  script:
    - echo "[deploy prod] COMMIT_ID $CI_BUILD_REF"
    - docker tag cm-dev-04.bwcmtg.com:5000/retail-portal:$CI_BUILD_REF cm-dev-04.bwcmtg.com:5000/retail-portal:prod-latest
    - docker push cm-dev-04.bwcmtg.com:5000/retail-portal:$CI_BUILD_REF
    - docker push cm-dev-04.bwcmtg.com:5000/retail-portal:prod-latest
    - scp $CI_PROJECT_DIR/*.yml devops@www.commercehomemortgage.com:~/services/
    - ssh -v devops@www.chmmarketingportal.com "cd /home/devops/services && ./retail-portal-deploy.sh $CI_BUILD_REF"
  only:
    - production
  tags:
    - production

dev_cleanup:
  stage: cleanup
  script:
    - echo "[Cleanup] COMMIT_ID $CI_BUILD_REF"
    - docker-compose -f docker-compose.yml stop
    - docker-compose -f docker-compose.yml rm -f
  only:
    - master
  tags:
    - development,docker,retail-portal
    
prod_cleanup:
  stage: cleanup
  script:
    - echo "[Cleanup] COMMIT_ID $CI_BUILD_REF"
    - docker-compose -f docker-compose.yml -f docker-compose.prod_override.yml stop
    - docker-compose -f docker-compose.yml -f docker-compose.prod_override.yml rm -f
  only:
    - production
  tags:
    - production
