# Shared dev env version of our application composition file for chmmarketingportal.com retail website app.
#
# Builds the full application from 2 images - web (rails app), db (currently mysql).
# nginx is not used in dev.
#
# Webapp application files are added during the docker image build and remain contained in the image.  The
# db files are volue-mounted from the host.  The db database files survive new container builds/deploys.
#
# This file:
#   - Allows for lifecycle management of the app - start, stop, restart, initial up, pulling of new container versions, etc.
#   - Mostly inherits baked-in defaults for dev
#   - Does not use nginx as a static content server; connect to puma port directly
#   - Exposes log files to host filesystem for dev monitoring
#   - DB port can be accessed from host to allow for db tool use
#   - Currently specified 1 thread per worker process.  This must remain like this until the app is tested in multi-threaded mode
#   - Pulls the web image from the CHM docker repository.  Edit "image: " line for using a local docker image.
version: '2'
services:
  web:
    # From our in-house docker repository
    image: cm-dev-04.bwcmtg.com:5000/retail-portal:$CI_BUILD_REF
    depends_on:
      - db
    environment:
      - COMMIT_ID=$CI_BUILD_REF
      - RACK_ENV=development
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - DB_PASS=nuggets6
      - DB_USER=dbuser
    links:
      - db
    ports:
      - "5050:5050"
    volumes:
      - retail-portal-web:/srv/www/htdocs
      - retail-portal-web-system:/srv/www/htdocs/public/system
      # Will likely be used in future
      # - /srv/www/logos:/srv/www/htdocs/public/logos
      # - /srv/www/loan-officer-images:/srv/www/htdocs/public/LOImages
      # - /srv/www/loan-officer-signatures:/srv/www/htdocs/public/LOSignatures
      # - /srv/www/lobw-photos:/srv/www/htdocs/public/LOBWPhotos
    restart: always
  db:
    #image: postgres:9.5
    image: sameersbn/postgresql:9.5-3
    expose:
      - "5432"
    environment:
      - DB_PASS=nuggets6
      - DB_USER=dbuser
      - DB_NAME=portal_dev
      - USERMAP_UID=999
      - USERMAP_GID=999
      - DB_EXTENSION=pg_trgm
    volumes:
      - retail-portal-db:/var/lib/postgresql
    restart: always
volumes:
  retail-portal-web:
  retail-portal-db:
    driver: nfs
    driver_opts:
      share: 10.254.4.119:/webdata/retail-portal/db/development
  retail-portal-web-system:
    driver: nfs
    driver_opts:
      share: 10.254.4.119:/webdata/retail-portal/web/system
