development:
  adapter: postgresql
  encoding: unicode
  database: portal_dev
  pool: 5
  username: postgres
  password: nuggets6
  host: db
test:
  adapter: postgresql
  encoding: unicode
  database: portal_test
  pool: 5
  username: postgres
  password:
  host: db
production:
  adapter: postgresql
  encoding: unicode
  database: portal_prod
  pool: 5
  username: postgres
  password: ENV['POSTGRES_PASSWORD']
  host: db
