development:
  adapter: postgresql
  encoding: unicode
  database: portal_dev
  pool: 5
  username: ENV['DB_USER']
  password: ENV['DB_PASS']
  host: db
test:
  adapter: postgresql
  encoding: unicode
  database: portal_test
  pool: 5
  username: ENV['DB_USER']
  password: ENV['DB_PASS']
  host: db
production:
  adapter: postgresql
  encoding: unicode
  database: portal_prod
  pool: 5
  username: ENV['DB_USER']
  password: ENV['DB_PASS']
  host: db
