development:
  adapter: postgresql
  encoding: unicode
  database: portal_dev
  pool: 5
  username: postgres
  password: 
  host: localhost
  port: 5442
test:
  adapter: postgresql
  encoding: unicode
  database: portal_test
  pool: 5
  username: postgres
  password:
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: portal_prod
  pool: 5
  username: postgres
  password: ENV['POSTGRES_PASSWORD']
  host: localhost